### ISSUE TITLE
Docker 部署 无法正常显示页面

### ISSUE THREAD

**Issue by Jkkoi** [Dooy/chatgpt-web-midjourney-proxy#379]
在移动设备上，只会显示一个 Aha，其他地方都为空白
![11](https://github.com/Dooy/chatgpt-web-midjourney-proxy/assets/39653010/5a1b85a3-90d6-4e29-a0b6-3db5cdb6f525)

所用的 docker-compose 如下
```yml
services:
  chatgpt-web-midjourney-proxy:
    image: ydlhero/chatgpt-web-midjourney-proxy
    container_name: chatgpt-web-midjourney-proxy
    ports:
      - "3002:3002"
    environment:
      - OPENAI_API_KEY=sk-1145141919810
      - OPENAI_API_BASE_URL=https://example.com
      - API_UPLOADER=1  
      - HIDE_SERVER=1
      - SYS_NOTIFY=1
    restart: always
```

Nginx 部分配置如下：
```
    # reverse proxy
    location / {
        proxy_pass            http://chatgpt-web-midjourney-proxy:3002;
        proxy_set_header Host $host;
        proxy_http_version                 1.1;
        proxy_cache_bypass                 $http_upgrade;

        # Proxy SSL
        proxy_ssl_server_name              on;

        # Proxy headers
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        $connection_upgrade;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header Forwarded         $proxy_add_forwarded;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host  $host;
        proxy_set_header X-Forwarded-Port  $server_port;

        # Proxy timeouts
        proxy_connect_timeout              60s;
        proxy_send_timeout                 60s;
        proxy_read_timeout                 60s;
    }
```

手机浏览器为 firefox 版本 `125.3.0 (Build #2016017554)`，QQ微信内置浏览器存在同样问题
