### ISSUE TITLE
如何自定义下拉列表

### ISSUE THREAD

**Issue by zu-ke** [Dooy/chatgpt-web-midjourney-proxy#595]
你好，这个下拉列表可选模型怎么自定义？
![xx](https://imgbed.zukedog.cn/i/2025/02/10/u17cyw.png)
下面是我的docker-compose.yml文件：
```yaml
version: '3'

services:
  gptweb:
    container_name: chatgpt-web-midjourney-proxy
    image: ydlhero/chatgpt-web-midjourney-proxy 
    ports:
      - xxxx:3002
    environment:
      TZ: Asia/Shanghai # 指定时区
      # 必选
      OPENAI_API_KEY: sk-xxxx
      # HIDE_SERVER 隐藏服务端 1，可选
      # HIDE_SERVER: 1
      # UPLOAD_IMG_SIZE gpt-4-version 图片上传大小 单位是兆 注意别带单位 最好别超过10 
      UPLOAD_IMG_SIZE: 50
      # 支持上传
      API_UPLOADER: 1
      # 上传方式
      UPLOAD_TYPE: Container
      # 禁用菜单
      MENU_DISABLE: music,video,dance,realtime
      # 识图模型
      VISION_MODEL: gpt-4o
      # 自定义可选模型
      CUSTOM_MODELS: gpt-4o,gemini-2.0-flash
```
